covid_ppw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tracker/', include('tracker.urls'), name='tracker'),
    path('quiz/', include('quiz.urls'), name='quiz'),
    path('todolist/', include('todolist.urls'), name='todolist'),
    path('report/', include('report.urls'), name='report'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('save/', views.save, name='save'),
]

report/models.py
from django.db import models

# Create your models here.
class Suspect(models.Model):
    nama_suspek = models.CharField(max_length=30)
    alamat = models.CharField(max_length=200)
    tanggal_lahir = models.DateField()
    status = models.CharField(max_length=15)

report/forms.py
from django import forms
from .models import Suspect

class SearchForm(forms.ModelForm):
    class Meta:
        model = Suspect
        fields = ['nama_suspek']

    name_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Search by name',
        'name' : 'nama_suspek',
	}

    nama_suspek = forms.CharField(label='', required= True, max_length=50, widget=forms.TextInput(attrs=name_attrs))

class SuspectForm(forms.ModelForm):
    class Meta:
        model = Suspect
        fields = ['nama_suspek', 'alamat', 'tanggal_lahir']

    name_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Enter the name',
        'name' : 'nama_suspek',
	}

    address_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Address',
        'name' : 'alamat',
	}

    birthdate_attrs = {
        'class' : 'form-control mb-3',
        'type' : 'date',
        'placeholder' : 'Date of Birth',
        'name' : 'tanggal_lahir',
    }

    selfpict_attrs = {
        'class' : 'form-control mb-3',
        'type' : 'file',
        'value' : 'Upload photo',
        'name' : 'foto_diri',
    }

    idpict_attrs = {
        'class' : 'form-control mb-3',
        'type' : 'file',
        'value' : 'Upload identity card',
        'name' : 'foto_ktp',
    }

    nama_suspek = forms.CharField(label='', required= True, max_length=50, widget=forms.TextInput(attrs=name_attrs))
    alamat = forms.CharField(label='Alamat', required= True, max_length=200, widget=forms.TextInput(attrs=address_attrs))
    tanggal_lahir = forms.DateField(label='Tanggal Lahir', required= True, widget=forms.TextInput(attrs=birthdate_attrs))
    #foto_diri = forms.ImageField(label='Foto Diri', required= True, widget=forms.TextInput(attrs=selfpict_attrs))
    #foto_ktp = forms.ImageField(label='Foto KTP', required= True, widget=forms.TextInput(attrs=idpict_attrs))

report/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import SuspectForm, SearchForm
from .models import Suspect

response = {}
# Create your views here.


def index(request):
    suspects = Suspect.objects.all()
    response['suspects'] = suspects
    response['search'] = SearchForm()
    response['toggle'] = "collapse"
    if (request.method == "POST" and 'nama_suspek' in request.POST):
        target = SearchForm(request.POST)
        if (target.is_valid()):
            data_target = target.cleaned_data
            data = []
            for suspect in suspects:
                if data_target['nama_suspek'].lower() in suspect.nama_suspek.lower():
                    data.append(suspect)
            response['suspects'] = data
            response['toggle'] = "collapse show"
    return render(request, 'report/index.html', response)


def new(request):
    response = {'inputForm': SuspectForm}
    return render(request, 'report/form.html', response)


def save(request):
    form = SuspectForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        data_form = form.cleaned_data
        data_input = Suspect()
        data_input.nama_suspek = data_form['nama_suspek']
        data_input.alamat = data_form['alamat']
        data_input.tanggal_lahir = data_form['tanggal_lahir']
        data_input.status = "Not Confirmed"
        data_input.save()
    return HttpResponseRedirect('/report/')

report/templates/report/form.html
{% extends 'templates/base.html' %}

{% block meta %}
    <title>Report - Survive COVID</title>
{% endblock meta %}

{% block content %}
<div style="min-height: 600px;">
    <p class="header center">Report The Suspect</p>
    <p class="button-text-dummy center">Complete the suspect’s biodata below.</p>
    </br>
    <form id="form" method="POST" action="/report/save/">
            {% csrf_token %}
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Nama</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.nama_suspek }}</p>
            </div>
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Alamat</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.alamat }}</p>
            </div>
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Tanggal Lahir</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.tanggal_lahir }}</p>
            </div>
            <div class="center">
                <input id="submit" type="submit" class="cta m-5 cta-text text-shadow" value="Submit">
            </div>
    </form>
</div>
    
{% endblock content %}

report/templates/report/index.html
{% extends 'templates/base.html' %}

{% block meta %}
    <title>Report - Survive COVID</title>
{% endblock meta %}

{% block content %}
<div style="min-height: 600px;">
    <p class="main-title text-glow center">Report</p>
    <p class="button-text-dummy center">This feature is useful for seeing and reporting suspects around you.</p>
    <br>
    <div class="center">
        <a href="{% url 'report:new' %}">
            <button class="cta">
                <p class="cta-text text-shadow">+ New Report</p>
            </button>
        </a>
        <a href="#collapseDataReport" data-toggle="collapse" aria-expanded="false" aria-controls="collapseDataReport">
            <button class="shadow-cta" >
                <p class="shadow-cta-text">See Report</p>
            </button>
        </a>
    </div>
    <br>
    <div class="{{ toggle }}" id="collapseDataReport">
        {% if suspects %}
        <form method="POST">
            {% csrf_token %}
            <div>
                {{ search }}
                <p class="cta-text text-shadow"><input type='submit' class="cta cta-text text-shadow" value="Search"></p>
            </div>
        </form>
        <br>
        <table class="table table-bordered" style="background-color: var(--green-bg);">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Birth Date</td>
                    <td>Address</td>
                    <td>Status</td>
                </tr>
            </thead>
            <tbody>
                {% for person in suspects %}
                <tr>
                    <td>{{ person.nama_suspek}}</td>
                    <td>{{ person.tanggal_lahir }}</td>
                    <td>{{ person.alamat }}</td>
                    <td>{{ person.status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="text center">No data avalaible<p>
        {% endif %}
    </div>
</div>
    
{% endblock content %}